import type { Metadata } from "next";
// import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <div className="background">
          <FlowyCloth />
          <Silk
            speed={5}
            scale={1}
            color="#2fab05"
            noiseIntensity={1}
            rotation={0}
          />
        </div> */}

        <style>{`
        

        body {
          display: grid;
          place-items: center;
          background: light-dark(white, black);
          min-height: 100vh;
          font-family: 'Geist';
          margin: 0;
          padding: 0;
        }

        body::before {
          --size: 45px;
          --line: color-mix(in hsl, canvasText, transparent 70%);
          content: '';
          height: 100vh;
          width: 100vw;
          position: fixed;
          background: linear-gradient(
                90deg,
                var(--line) 1px,
                transparent 1px var(--size)
              )
              50% 50% / var(--size) var(--size),
            linear-gradient(var(--line) 1px, transparent 1px var(--size)) 50% 50% /
              var(--size) var(--size);
          mask: linear-gradient(-20deg, transparent 50%, white);
          top: 0;
          transform-style: flat;
          pointer-events: none;
          z-index: -1;
        }

        html {
          color-scheme: light dark;
        }

        // [data-theme='light'] {
        //   color-scheme: light only;
        // }

        // [data-theme='dark'] {
        //   color-scheme: dark only;
        // }
      `}</style>

        {children}
      </body>
    </html>
  );
}
