import type { Metadata } from "next";
// import { Geist } from "next/font/google";
// import { GeistSans } from "geist/font/sans";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const geist = Geist({
//   subsets: ['latin'],
//   variable: '--font-geist',
// })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="font-bold">
        {children}
      </body>
    </html>
  );
}
